name: Docker container ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build-container:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Prepare
      run: |
          docker build --tag next .
          docker run --detach --publish 5000:3000 next
    
    - name: Login to DockerHub
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: ronaofer/myfirstimage
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
