name: docker Build and Publish

on:
   # run it on push to the default repository branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-docker:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
		  image: ronaofer/myfirstimage
		  registry: docker.io
		  username: ${{ secrets.DOCKER_USERNAME }}
		  password: ${{ secrets.DOCKER_PASSWORD }}
